version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo Install started on `date`
      - apt-get install unzip
      - wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
      - unzip packer_${PACKER_VERSION}_linux_amd64.zip
      - mv packer /usr/local/bin/
      - packer -version
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - |
        cat << EOF > ubuntu.json
        {
          "builders": [{
            "type": "amazon-ebs",
            "region": "${AWS_REGION}",
            "source_ami_filter": {
              "filters": {
                "virtualization-type": "hvm",
                "name": "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*",
                "root-device-type": "ebs"
              },
              "most_recent": true
            },
            "instance_type": "t2.micro",
            "ssh_username": "ubuntu",
            "ami_name": "awsbot-ubuntu {{timestamp}}"
          }]
        }
        EOF
      - packer validate ubuntu.json
  build:
    commands:
      - echo Build started on `date`
      - packer build -color=false ubuntu.json
  post_build:
    commands:
      - echo Post-build started on `date`
artifacts:
  files:
    - '**/*'